services:
  react-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      VITE_WS_URL: ws://localhost:3002
    ports:
      - "3000:3000"
  poker-backend:
    build:
      context: .
      dockerfile: game_engine/Dockerfile
    ports:
      - "3002:3002"
